import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {
    private String firstName;
    private String lastName;
    private String email;

    /* Check target/classes/User.class to see the methods generated by Lombok */
    public static void main(String[] args) {
        User user = new User("Pham", "Diep", "dp@gmail.com");
        System.out.println(user);
    }
}